// <auto-generated />
using System;
using EMenuApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EMenuApplication.Migrations
{
    [DbContext(typeof(EMenuDBContext))]
    [Migration("20200821183211_Add_Emenu_CategoryConcepts")]
    partial class Add_Emenu_CategoryConcepts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EMenuApplication.Models.CRM_CQuestions", b =>
                {
                    b.Property<int>("q_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modifiedon")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<int?>("cqg_id")
                        .HasColumnType("int");

                    b.Property<string>("q_managerperformanace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q_question")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q_shortdescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("q_status")
                        .HasColumnType("smallint");

                    b.HasKey("q_id");

                    b.ToTable("CRM_CQuestions");
                });

            modelBuilder.Entity("EMenuApplication.Models.CRM_CQuestionsGroups", b =>
                {
                    b.Property<int>("cqg_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ServerPerformance")
                        .HasColumnType("bit");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("cqg_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cqg_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("cqg_status")
                        .HasColumnType("smallint");

                    b.HasKey("cqg_id");

                    b.ToTable("CRM_CQuestionsGroups");
                });

            modelBuilder.Entity("EMenuApplication.Models.CRM_CommentCard", b =>
                {
                    b.Property<int>("cc_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("AvgScore")
                        .HasColumnType("bit");

                    b.Property<string>("CCBackground")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCBorderWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCControlsBorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CCCustomFont")
                        .HasColumnType("bit");

                    b.Property<string>("CCCustomFontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCustomFontFile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCustomFontFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCCustomFontLocal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCFontColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCFontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCFontSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCFontStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCFontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCLeftImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCRightImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCfooterHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCfooterIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCheaderHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCheaderIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ColorCoded")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedBy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Notify_Bymail")
                        .HasColumnType("bit");

                    b.Property<bool?>("Notify_Bysms")
                        .HasColumnType("bit");

                    b.Property<string>("PRBorderWidth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRControlsBorderColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRFontColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRFontFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRFontSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRFontStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRFontWeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRfooterHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRfooterIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRheaderHeight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRheaderIMG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileLeftImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileRightImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileTitle1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitbtnBackColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmitbtnForeColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThankYouImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<string>("cc_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("cc_minvalue")
                        .HasColumnType("int");

                    b.Property<string>("cc_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("ct_status")
                        .HasColumnType("smallint");

                    b.Property<bool?>("linebased")
                        .HasColumnType("bit");

                    b.HasKey("cc_id");

                    b.ToTable("CRM_CommentCard");
                });

            modelBuilder.Entity("EMenuApplication.Models.CRM_CommentCardQuestions", b =>
                {
                    b.Property<int>("ccq_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("AnswerFullSpace")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modifiedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Relatedquestion")
                        .HasColumnType("int");

                    b.Property<bool?>("ShowQuestionText")
                        .HasColumnType("bit");

                    b.Property<int>("cc_id")
                        .HasColumnType("int");

                    b.Property<int?>("cqg_order")
                        .HasColumnType("int");

                    b.Property<bool?>("cqg_visible")
                        .HasColumnType("bit");

                    b.Property<string>("q_answerDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("q_bootstrapSkin")
                        .HasColumnType("bit");

                    b.Property<bool?>("q_calculated")
                        .HasColumnType("bit");

                    b.Property<int>("q_id")
                        .HasColumnType("int");

                    b.Property<bool?>("q_linebased")
                        .HasColumnType("bit");

                    b.Property<int?>("q_minval")
                        .HasColumnType("int");

                    b.Property<int?>("q_ordre")
                        .HasColumnType("int");

                    b.Property<bool?>("q_required")
                        .HasColumnType("bit");

                    b.Property<string>("q_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("q_typevalue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("q_weight")
                        .HasColumnType("int");

                    b.Property<short?>("status")
                        .HasColumnType("smallint");

                    b.Property<string>("textPlaceholder")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ccq_id");

                    b.ToTable("CRM_CommentCardQuestions");
                });

            modelBuilder.Entity("EMenuApplication.Models.CRM_CommentCardResults", b =>
                {
                    b.Property<int>("ctr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CCR_ID")
                        .HasColumnType("int");

                    b.Property<string>("Calculated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineBased")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Required")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctr_AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctr_answer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ctr_score")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("q_id")
                        .HasColumnType("int");

                    b.Property<string>("q_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ctr_id");

                    b.ToTable("CRM_CommentCardResults");
                });

            modelBuilder.Entity("EMenuApplication.Models.CRM_CommentCardResultsHeader", b =>
                {
                    b.Property<int>("CCR_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("AccountID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActNbreCall")
                        .HasColumnType("int");

                    b.Property<string>("ActNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Act_Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Act_lastStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Act_lastUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Act_lastcalled")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Actactive")
                        .HasColumnType("bit");

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<decimal?>("Avgscore")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("BadgeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("COR")
                        .HasColumnType("int");

                    b.Property<string>("CallAgentNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("CaseCreated")
                        .HasColumnType("bit");

                    b.Property<int?>("Checkno")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Concept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("Customer_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImmediateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImmediateUserDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastCall")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaritalStatus_ID")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Nationality")
                        .HasColumnType("int");

                    b.Property<int?>("NoCall")
                        .HasColumnType("int");

                    b.Property<string>("OperationalReporting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParamValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Params")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Promo")
                        .HasColumnType("real");

                    b.Property<float>("QSA")
                        .HasColumnType("real");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<string>("SecondaryMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ServiceAVGscore")
                        .HasColumnType("real");

                    b.Property<string>("StoreTimezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Store_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Storeno")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synchronized")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tableno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TimeCreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Waiter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<int?>("cc_id")
                        .HasColumnType("int");

                    b.Property<string>("company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("salutation_id")
                        .HasColumnType("int");

                    b.Property<byte?>("status")
                        .HasColumnType("tinyint");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("CCR_ID");

                    b.ToTable("CRM_CommentCardResultsHeader");
                });

            modelBuilder.Entity("EMenuApplication.Models.CRM_CommentCardStores", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("Store_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("active")
                        .HasColumnType("bit");

                    b.Property<int>("cc_id")
                        .HasColumnType("int");

                    b.Property<bool?>("selected")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("CRM_CommentCardStores");
                });

            modelBuilder.Entity("EMenuApplication.Models.Category_Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category_Sequence");
                });

            modelBuilder.Entity("EMenuApplication.Models.Concept_Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Concept_Theme");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConceptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailsAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Emenu_Category");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_CategoryConcepts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emenu_CategoryConcepts");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SymbolAR")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emenu_Currency");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_ItemTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConceptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconTagName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Emenu_ItemTags");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_ItemTagsConcepts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emenu_ItemTagsConcepts");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_MenuItemTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EMenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emenu_MenuItemTags");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_MenuItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CommentsAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentsEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConceptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailsAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetailsEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LargeDetailsAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LargeDetailsEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LargeImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverLayImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverlayDetailsAR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverlayDetailsEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PLU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("ThumbnailImageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emenu_MenuItems");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_MenuMItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EMenuItemsId")
                        .HasColumnType("int");

                    b.Property<int>("EMenusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Emenu_MenuMItems");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_MenuSchedules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConceptId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("Store_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UniqueCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emenu_MenuSchedules");
                });

            modelBuilder.Entity("EMenuApplication.Models.Emenu_Menus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConceptId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Emenu_Menus");
                });

            modelBuilder.Entity("EMenuApplication.Models.Item_Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Item_Sequence");
                });

            modelBuilder.Entity("EMenuApplication.Models.Sec_UserStores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("Store_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sec_UserStores");
                });

            modelBuilder.Entity("EMenuApplication.Models.Sec_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<bool?>("CanExportProfiles")
                        .HasColumnType("bit");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultModule")
                        .HasColumnType("int");

                    b.Property<int?>("DefaultPage")
                        .HasColumnType("int");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoggedIn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Lock")
                        .HasColumnType("bit");

                    b.Property<bool?>("LockProfile")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.Property<bool?>("UnlockProfile")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sec_Users");
                });

            modelBuilder.Entity("EMenuApplication.Models.Set_Concepts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ConceptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Set_Concepts");
                });

            modelBuilder.Entity("EMenuApplication.Models.Set_CountryCodes", b =>
                {
                    b.Property<int>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Digits")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("minDigits")
                        .HasColumnType("int");

                    b.Property<string>("timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Set_CountryCodes");
                });

            modelBuilder.Entity("EMenuApplication.Models.Set_Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Set_Region");
                });

            modelBuilder.Entity("EMenuApplication.Models.Set_Stores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CCEmailRecipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCSMSReceipient")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommentCardAutoFill")
                        .HasColumnType("bit");

                    b.Property<int>("Conceptid")
                        .HasColumnType("int");

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency_ID")
                        .HasColumnType("int");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ListOrder")
                        .HasColumnType("int");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Regionid")
                        .HasColumnType("int");

                    b.Property<int>("SquirrelCurrency")
                        .HasColumnType("int");

                    b.Property<int>("SquirrelID")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StoreCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Store_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Store_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Set_Stores");
                });

            modelBuilder.Entity("EMenuApplication.Models.Sys_FieldValues", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sys_FieldValues");
                });

            modelBuilder.Entity("EMenuApplication.Models.Sys_Fields", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CSS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Col")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("CustomField")
                        .HasColumnType("bit");

                    b.Property<string>("DataType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Incomplete")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModuleID")
                        .HasColumnType("int");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<bool?>("Readonly")
                        .HasColumnType("bit");

                    b.Property<bool?>("Required")
                        .HasColumnType("bit");

                    b.Property<string>("RequiredMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredPattern")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredPatternMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SectionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceTable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.Property<bool?>("hasActive")
                        .HasColumnType("bit");

                    b.Property<string>("sourcePageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sys_Fields");
                });

            modelBuilder.Entity("EMenuApplication.Models.set_DropDown", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DD_Display")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD_Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DD_ValueOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("set_DropDown");
                });
#pragma warning restore 612, 618
        }
    }
}
